//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "loans"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub date_created: DateTime,
    pub date_updated: DateTime,
    pub principal: Decimal,
    pub rate: Decimal,
    pub number_of_months: Decimal,
    pub monthly_payment: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    DateCreated,
    DateUpdated,
    Principal,
    Rate,
    NumberOfMonths,
    MonthlyPayment,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::DateCreated => ColumnType::DateTime.def(),
            Self::DateUpdated => ColumnType::DateTime.def(),
            Self::Principal => ColumnType::Decimal(None).def(),
            Self::Rate => ColumnType::Decimal(None).def(),
            Self::NumberOfMonths => ColumnType::Decimal(None).def(),
            Self::MonthlyPayment => ColumnType::Decimal(None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
